# Generated by Django 5.0.6 on 2024-05-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_delete_listingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reservation_list',
            field=models.ManyToManyField(blank=True, related_name='reservation_users', to='core.listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='trip_list',
            field=models.ManyToManyField(blank=True, related_name='trip_users', to='core.listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(blank=True, related_name='wish_users', to='core.listing'),
        ),
    ]
