# Generated by Django 5.0.6 on 2024-05-24 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('apt_suite', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('guest_count', models.IntegerField()),
                ('bedroom_count', models.IntegerField()),
                ('bed_count', models.IntegerField()),
                ('bathroom_count', models.IntegerField()),
                ('amenities', models.JSONField(default=list)),
                ('listing_photo_paths', models.JSONField(default=list)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('highlight', models.CharField(max_length=255)),
                ('highlight_desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
