# Generated by Django 5.0.6 on 2024-05-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listingphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingPhoto',
        ),
    ]
